  function renderContractors(){
    return guideStrip('contractors','Registra la empresa contratista y sus datos básicos. Si ya existe, revisa su historial antes de crear un nuevo contrato.','Una ficha maestra de la contratista que podrás reutilizar en futuros contratos.')+`<div class="toolbar"><div class="toolbar-left"><input class="input search" id="contractorSearch" placeholder="Buscar por empresa, RIF o contacto"></div><div class="toolbar-right"><button class="btn btn-ghost" data-action="import">Importar respaldo</button><button class="btn btn-primary" data-action="new-contractor">+ Contratista</button></div></div><div class="section panel"><div class="section-head"><div><h3>Directorio de contratistas</h3><p>Ficha maestra e historial de contratación.</p></div><span class="muted small">${state.contractors.length} registradas</span></div><div id="contractorsTable">${contractorsTable(state.contractors)}</div></div>`+stepNav('contractors');
  }
  function contractorsTable(rows){
    if(!rows.length) return '<div class="empty"><strong>No se encontraron contratistas</strong>Modifica la búsqueda o registra una nueva empresa.</div>';
    return `<div class="table-wrap"><table class="table"><thead><tr><th>Empresa</th><th>RIF</th><th>Contacto</th><th>Contratos</th><th>Último resultado</th><th></th></tr></thead><tbody>${rows.map(x=>{const contracts=state.contracts.filter(c=>c.contractorId===x.id); const last=contracts.at(-1);return `<tr><td><strong class="text-navy">${esc(x.name)}</strong><div class="small muted">${esc(x.email||'')}</div></td><td>${esc(x.rif||'—')}</td><td>${esc(x.contact||'—')}<div class="small muted">${esc(x.phone||'')}</div></td><td>${contracts.length}</td><td>${last?statusTag(last.status):tag('Sin historial','gray')}</td><td class="right"><button class="btn btn-ghost btn-sm" data-edit-contractor="${x.id}">Editar</button></td></tr>`}).join('')}</tbody></table></div>`;
  }

  function renderContracts(){
    const c=activeContract();
    return guideStrip('contracts','Define el alcance real del trabajo: ubicación, fechas, cantidad de personas, subcontratación, tareas críticas e interfaces previsibles.','Un expediente contractual suficientemente claro para evaluar el nivel de control necesario.')+`<div class="toolbar"><div class="toolbar-left"><span class="muted small">Gestiona el expediente SST desde la planificación hasta el cierre.</span></div><div class="toolbar-right"><button class="btn btn-primary" data-action="new-contract">+ Nuevo contrato</button></div></div><div class="section panel">${contractsTable(state.contracts)}</div>${c?`<div class="section grid grid-2"><div class="panel"><h3 class="panel-title">Ficha del contrato activo</h3><div class="form-grid"><div class="field"><label>Estado</label><select class="select" id="contractStatus">${selectHtml(STAGES,c.status)}</select></div><div class="field"><label>Contratista</label><div class="input">${esc(contractorById(c.contractorId)?.name||'')}</div></div><div class="field"><label>Inicio</label><div class="input">${fmtDate(c.start)}</div></div><div class="field"><label>Fin previsto</label><div class="input">${fmtDate(c.end)}</div></div><div class="field full"><label>Alcance</label><textarea class="textarea" id="contractScope">${esc(c.scope||'')}</textarea></div></div><div class="actions"><button class="btn btn-primary" data-action="save-contract-meta">Guardar cambios</button></div></div><div class="panel"><h3 class="panel-title">Tareas críticas e interfaces</h3><div class="status-row">${(c.tasks||[]).map(t=>tag(t,'navy')).join('')||tag('No definidas','gray')}</div><div class="callout info mt-16"><strong>Criterio:</strong> las tareas críticas no se usan como una etiqueta general del contrato. Sirven para definir competencias, controles, permisos, interfaces y verificación específica.</div><div class="actions"><button class="btn btn-ghost" data-action="edit-tasks">Editar tareas</button></div></div></div>`:''}`+stepNav('contracts');
  }

  function requireContract(){ const c=activeContract(); return c || null; }
  function noContract(){ return '<div class="empty"><strong>Selecciona o crea un contrato</strong>Este módulo se aplica sobre un contrato específico.</div>'; }

  function renderCriticality(){
    const c=requireContract(); if(!c) return noContract(); const r=criticalityResult(c);
    return guideStrip('criticality','Valora de 1 a 5 exposición, severidad potencial, complejidad, interfaces y subcontratación. Piensa en el alcance concreto, no en la reputación de la empresa.','Nivel 1, 2 o 3 para decidir cuánta profundidad exigir en precalificación, preinicio y seguimiento.')+`<div class="hero-panel"><div class="kicker">Instrumento 2 integrado</div><h2>Clasificación de criticidad</h2><p>La criticidad determina la intensidad del control. No es un sinónimo de “trabajo peligroso”; combina exposición, severidad, complejidad, interfaces y subcontratación.</p></div><div class="section grid grid-2"><div class="panel"><h3 class="panel-title">Factores del contrato</h3>${CRIT_FACTORS.map(([k,n,d])=>`<div class="risk-row"><div><div class="strong text-navy">${n}</div><div class="small muted">${d}</div></div><input class="range crit-range" data-key="${k}" type="range" min="1" max="5" step="1" value="${Number(c.criticality?.[k])||1}"><div class="range-value" id="crit-${k}">${Number(c.criticality?.[k])||1}</div></div>`).join('')}</div><div class="panel"><div class="result-card"><div class="result-label">Resultado</div><div class="result-value" id="critTotal">${r.total}/25</div><div class="mt-8">${tag(r.level,r.short==='N3'?'yellow':r.short==='N2'?'teal':'green')}</div><div class="progress mt-12"><span id="critProgress" style="width:${r.total/25*100}%"></span></div></div><div class="callout info mt-12"><strong>Nivel 1:</strong> control simplificado, proporcional al alcance.<br><strong>Nivel 2:</strong> control estándar con verificación formal.<br><strong>Nivel 3:</strong> control reforzado, mayor profundidad de precalificación, preinicio y seguimiento.</div><div class="callout warn mt-12">La escala es una metodología del curso. Debe aprobarse internamente antes de utilizarse como criterio corporativo formal.</div></div></div>`+stepNav('criticality');
  }

  function renderPrequal(){
    const c=requireContract(); if(!c) return noContract(); const r=prequalResult(c); const s=c.prequal?.scores||{}; const b=c.prequal?.blockers||{};
    return guideStrip('prequal','Evalúa la capacidad SST de la contratista con evidencia. Revisa especialmente los criterios críticos y marca cualquier condición bloqueante.','Decisión técnica: habilitada, habilitada con condiciones o no habilitada para este alcance.')+`<div class="section grid grid-3"><div class="result-card"><div class="result-label">Capacidad SST</div><div class="result-value" id="pqScore">${pct(r.score)}%</div><div class="progress mt-12"><span id="pqProgress" style="width:${r.score}%"></span></div></div><div class="result-card"><div class="result-label">Decisión</div><div class="result-value" id="pqDecision" style="font-size:20px">${r.decision}</div><div class="small muted mt-8">El puntaje no compensa una condición bloqueante.</div></div><div class="result-card"><div class="result-label">Criticidad del contrato</div><div class="result-value">${criticalityResult(c).short}</div><div class="small muted mt-8">${criticalityResult(c).level}</div></div></div><div class="section grid grid-2"><div class="panel"><h3 class="panel-title">Evaluación de capacidad</h3><div class="small muted mb-0">Escala 0-4: 0 inexistente · 1 deficiente · 2 parcial · 3 satisfactorio · 4 robusto.</div>${PREQUAL.map(i=>`<div class="score-card"><div><div class="name">${esc(i.name)} ${i.critical?tag('CRÍTICO','yellow'):''}</div><div class="desc">${esc(i.desc)}</div></div><select class="score-select pq-score" data-key="${i.id}">${[0,1,2,3,4].map(v=>`<option value="${v}" ${Number(s[i.id])===v?'selected':''}>${v}</option>`).join('')}</select><div class="weight">${i.weight}%</div></div>`).join('')}</div><div><div class="panel"><h3 class="panel-title">Condiciones bloqueantes</h3>${[['criticalCompetence','No se demuestra una competencia crítica requerida'],['legalGap','Existe incumplimiento legal crítico no resuelto'],['criticalControl','No existe o no es confiable un control crítico requerido']].map(([k,n])=>`<label class="check-item flex between center mt-8"><span><strong class="text-navy">${n}</strong><div class="small muted">Si aplica, la contratista no debe habilitarse hasta cerrar la brecha.</div></span><input type="checkbox" class="pq-blocker" data-key="${k}" ${b[k]?'checked':''}></label>`).join('')}</div><div class="panel section"><h3 class="panel-title">Criterio técnico / condiciones</h3><textarea class="textarea" id="pqNotes" placeholder="Registre brechas, evidencia faltante y condiciones previas...">${esc(c.prequal?.notes||'')}</textarea><div class="actions"><button class="btn btn-primary" data-action="save-pq-notes">Guardar</button></div></div><div class="callout info section">Inspirado en la lógica de evaluación de capacidad de IOGP 423-01 y en la estructura venezolana de PDVSA SI-S-04. La escala y los umbrales de esta aplicación son una propuesta metodológica del curso.</div></div></div>`+stepNav('prequal');
  }

  function renderPrestart(){
    const c=requireContract(); if(!c) return noContract(); const r=prestartResult(c); const checks=c.prestart?.checks||{};
    return guideStrip('prestart','Antes de autorizar el trabajo, confirma condiciones de inicio y resuelve las interfaces entre beneficiaria, contratista y subcontratistas.','Una puerta de inicio documentada y un mapa de interfaces con responsabilidades, primacía y controles.')+`<div class="section grid grid-3"><div class="result-card"><div class="result-label">Cumplimiento</div><div class="result-value" id="psCompliance">${pct(r.compliance)}%</div><div class="progress mt-12"><span id="psProgress" style="width:${r.compliance}%"></span></div></div><div class="result-card"><div class="result-label">Puerta de inicio</div><div class="result-value" id="psDecision" style="font-size:19px">${r.decision}</div><div class="small muted mt-8">Los pendientes críticos deben cerrarse antes del inicio.</div></div><div class="result-card"><div class="result-label">Interfaces registradas</div><div class="result-value">${c.prestart?.interfaces?.length||0}</div><div class="small muted mt-8">Documento puente simplificado</div></div></div><div class="section panel"><div class="section-head"><div><h3>Puerta de preinicio</h3><p>Verifique que el contrato esté realmente listo para comenzar.</p></div><button class="btn btn-green btn-sm" data-action="apply-prestart-status">Aplicar decisión al estado</button></div><div class="check-list">${PRESTART.map(i=>`<div class="check-item ${i.critical?'critical':''}"><div class="check-top"><div><h4>${esc(i.title)}</h4><p>${esc(i.desc)}</p></div>${i.critical?tag('crítico','yellow'):''}</div><div class="tri-state">${[['yes','Sí'],['pending','Pendiente'],['no','No']].map(([v,l])=>`<button class="ps-state ${checks[i.id]===v?'active '+(v==='yes'?'yes':v==='no'?'no':'pending'):''}" data-id="${i.id}" data-value="${v}">${l}</button>`).join('')}</div></div>`).join('')}</div></div><div class="section panel"><div class="section-head"><div><h3>Mapa de interfaces</h3><p>Defina responsabilidades, primacía documental y brechas entre sistemas.</p></div><button class="btn btn-primary btn-sm" data-action="add-interface">+ Interfaz</button></div><div id="interfaces">${renderInterfaces(c)}</div></div>`+stepNav('prestart');
  }
  function renderInterfaces(c){
    const rows=c.prestart?.interfaces||[]; if(!rows.length) return '<div class="empty"><strong>Sin interfaces registradas</strong>Agrega al menos las actividades donde beneficiaria y contratista deban coordinar controles.</div>';
    return rows.map((x,i)=>`<div class="interface-card mt-8" data-interface="${i}"><div class="field"><label>Actividad / interfaz</label><input class="input int-field" data-k="activity" value="${esc(x.activity||'')}"></div><div class="field"><label>Beneficiaria</label><input class="input int-field" data-k="client" value="${esc(x.client||'')}"></div><div class="field"><label>Contratista</label><input class="input int-field" data-k="contractor" value="${esc(x.contractor||'')}"></div><div class="field"><label>Documento / criterio que prevalece</label><input class="input int-field" data-k="primacy" value="${esc(x.primacy||'')}"></div><div class="field"><label>Brecha</label><input class="input int-field" data-k="gap" value="${esc(x.gap||'')}"></div><div class="field"><label>Control / evidencia</label><input class="input int-field" data-k="control" value="${esc(x.control||'')}"></div><div class="field"><label>Acción</label><button class="btn btn-danger btn-sm" data-remove-interface="${i}">Eliminar</button></div></div>`).join('')+`<div class="actions"><button class="btn btn-primary" data-action="save-interfaces">Guardar interfaces</button></div>`;
  }

  function renderMonitoring(){
    const c=requireContract(); if(!c) return noContract(); const rows=c.monitoring||[]; const open=rows.filter(x=>x.status!=='Cerrada').length;
    return guideStrip('monitoring','Durante la ejecución registra cambios, verificaciones, hallazgos, decisiones y acciones. Prioriza lo que puede modificar el riesgo o la autorización.','Trazabilidad de la ejecución y evidencia para saber si los controles realmente funcionaron.')+`<div class="section grid grid-4"><div class="metric"><div class="k">Registros</div><div class="v">${rows.length}</div><div class="sub">Inspecciones, verificaciones y eventos</div></div><div class="metric"><div class="k">Abiertos</div><div class="v">${open}</div><div class="sub">Acciones pendientes</div></div><div class="metric"><div class="k">Cerrados</div><div class="v">${rows.length-open}</div><div class="sub">Con seguimiento completado</div></div><div class="metric alert-metric"><div class="k">Estado contrato</div><div class="v" style="font-size:18px">${esc(c.status)}</div><div class="sub">Actualiza según avance real</div></div></div><div class="section panel"><div class="section-head"><div><h3>Seguimiento de ejecución</h3><p>Registre hallazgos que cambien decisiones, no solo cantidad de inspecciones.</p></div><button class="btn btn-primary btn-sm" data-action="new-monitoring">+ Registro</button></div>${monitoringTable(c)}</div><div class="section grid grid-2"><div class="callout info"><strong>Preguntas para la verificación:</strong><br>¿Los controles siguen siendo efectivos? ¿Cambió el alcance? ¿Aparecieron nuevas interfaces? ¿Hay trabajos simultáneos no previstos? ¿Se cerraron las acciones anteriores?</div><div class="callout warn"><strong>Reevaluar cuando:</strong><br>cambie personal clave, equipos, procedimiento, entorno, subcontratistas, secuencia de trabajo o se produzca un incidente/alerta relevante.</div></div>`+stepNav('monitoring');
  }
  function monitoringTable(c){ const rows=c.monitoring||[]; if(!rows.length)return '<div class="empty"><strong>Sin seguimiento registrado</strong>Agrega la primera inspección, verificación, incidente o acción.</div>'; return `<div class="table-wrap"><table class="table"><thead><tr><th>Fecha</th><th>Tipo</th><th>Severidad</th><th>Hallazgo / decisión</th><th>Responsable</th><th>Compromiso</th><th>Estado</th><th></th></tr></thead><tbody>${rows.map(x=>`<tr><td>${fmtDate(x.date)}</td><td>${tag(x.type,'navy')}</td><td>${tag(x.severity,x.severity==='Crítica'||x.severity==='Mayor'?'red':'yellow')}</td><td>${esc(x.finding)}</td><td>${esc(x.owner||'—')}</td><td>${fmtDate(x.due)}</td><td>${tag(x.status,x.status==='Cerrada'?'green':x.status==='En curso'?'yellow':'red')}</td><td><button class="btn btn-ghost btn-sm" data-edit-monitoring="${x.id}">Editar</button></td></tr>`).join('')}</tbody></table></div>`; }

  function renderPerformance(){
    const c=requireContract(); if(!c) return noContract(); const p=c.performance||{}; const r=performanceResult(c);
    return guideStrip('performance','Evalúa el desempeño por dimensiones, revisa bloqueantes, documenta fortalezas y brechas, y emite una recomendación para futuras contrataciones.','Scorecard de cierre, aprendizaje y recomendación final incorporados al Excel y al PDF.')+`<div class="section grid grid-3"><div class="result-card"><div class="result-label">Resultado consolidado</div><div class="result-value" id="perfScore">${pct(r.score)}%</div><div class="progress mt-12"><span id="perfProgress" style="width:${r.score}%"></span></div></div><div class="result-card"><div class="result-label">Decisión de cierre</div><div class="result-value" id="perfDecision" style="font-size:18px">${r.decision}</div><div class="small muted mt-8">La decisión considera bloqueantes.</div></div><div class="result-card"><div class="result-label">Historial</div><div class="result-value">${state.contracts.filter(x=>x.contractorId===c.contractorId).length}</div><div class="small muted mt-8">Contrato(s) registrados para la empresa</div></div></div><div class="section panel"><h3 class="panel-title">Scorecard por dimensiones</h3><div class="dim-grid">${PERFORMANCE_DIMS.map(([k,n,w])=>`<div class="dim-card"><h4>${n}</h4><div class="score" id="dim-${k}">${Number(p[k])||0}%</div><input class="perf-range" data-key="${k}" type="range" min="0" max="100" step="5" value="${Number(p[k])||0}"><div class="small muted mt-8">Peso ${w}%</div></div>`).join('')}</div></div><div class="section grid grid-2"><div class="panel"><h3 class="panel-title">Condiciones bloqueantes</h3>${[['criticalLegal','Incumplimiento legal/contractual crítico no cerrado'],['criticalControl','Falla de control crítico sin corregir'],['overdueCritical','Acción crítica vencida al cierre'],['highPotential','Evento de alto potencial con debilidad de gestión no cerrada']].map(([k,n])=>`<label class="check-item flex between center mt-8"><span><strong class="text-navy">${n}</strong></span><input type="checkbox" class="perf-blocker" data-key="${k}" ${p.blockers?.[k]?'checked':''}></label>`).join('')}</div><div class="panel"><h3 class="panel-title">Aprendizaje para próxima contratación</h3><div class="field"><label>Fortalezas</label><textarea class="textarea" id="perfStrengths">${esc(p.strengths||'')}</textarea></div><div class="field mt-12"><label>Brechas / condiciones futuras</label><textarea class="textarea" id="perfGaps">${esc(p.gaps||'')}</textarea></div><div class="actions"><button class="btn btn-primary" data-action="save-performance-notes">Guardar</button><button class="btn btn-green" data-action="apply-close-status">Pasar a cierre</button></div></div></div><div class="section callout info">El scorecard combina indicadores preventivos y de resultado. Cero accidentes no significa automáticamente buen desempeño si los controles críticos, acciones o interfaces fueron débiles.</div>`+stepNav('performance');
  }

  function renderReferences(){
    const refs=[
      ['Legal venezolana','LOPCYMAT','Responsabilidad, obligaciones y exigencia de cumplimiento en SST para los supuestos aplicables a contratistas y beneficiarias.'],
      ['Legal venezolana','Reglamento Parcial de la LOPCYMAT','Participación, Comité de SST y disposiciones aplicables a intermediarios y contratistas.'],
      ['Legal venezolana','NT-04-2023','PSST propio de la contratista, planificación del impacto, adaptación al centro de trabajo y vigilancia del cumplimiento.'],
      ['Laboral','LOTTT, arts. 47-50','Diferencia contratación legítima, tercerización prohibida, contratista y obra inherente o conexa.'],
      ['Sectorial venezolana','PDVSA SI-S-04 Rev. 6 (2015)','Referencia sectorial para aptitud, plan específico, preinicio, evaluaciones parciales y evaluación final. No se presenta como obligación general.'],
      ['Internacional','IOGP 423','Ciclo de contratación, premovilización, movilización, ejecución, verificación, monitoreo y cierre.'],
      ['Internacional','IOGP 423-01','Evaluación de capacidad HSE y sistema de puntuación como referencia metodológica.'],
      ['Internacional','IOGP 423-02','HSE Plan y Bridging Document para resolver interfaces entre sistemas de gestión.'],
      ['Gestión del riesgo','ISO 31000 / IEC 31010','Arquitectura de decisión basada en riesgo y selección de técnicas de evaluación.'],
      ['Desempeño','ISO 45004','Seguimiento, medición, análisis y evaluación del desempeño de SST.']
    ];
    return `<div class="hero-panel"><div class="kicker">Mapa de referencias</div><h2>Diferenciar obligación, referencia y metodología</h2><p>La aplicación evita presentar una buena práctica internacional o una norma interna de PDVSA como si fuera legislación general venezolana.</p></div><div class="section grid grid-3">${refs.map(([type,name,desc])=>`<div class="ref-card"><span class="ref-badge">${esc(type)}</span><h4>${esc(name)}</h4><p>${esc(desc)}</p></div>`).join('')}</div><div class="section callout warn"><strong>Uso profesional:</strong> antes de adoptar umbrales, puntuaciones o decisiones automáticas como política corporativa, la organización debe definir y aprobar formalmente sus criterios internos, considerando su contexto, obligaciones y gobernanza.</div>`;
  }
