  function bindView(){
    $$('[data-go]').forEach(b=>b.onclick=()=>setView(b.dataset.go));
    $$('[data-open-contract]').forEach(b=>b.onclick=()=>{state.activeContractId=b.dataset.openContract;save();setView('contracts')});
    $$('[data-action]').forEach(b=>{ const a=b.dataset.action; if(a==='new-contract')b.onclick=()=>openContractModal(); if(a==='new-contractor')b.onclick=()=>openContractorModal(); if(a==='export')b.onclick=exportState; if(a==='import')b.onclick=()=>$('#importFile').click(); if(a==='save-contract-meta')b.onclick=saveContractMeta; if(a==='edit-tasks')b.onclick=editTasks; if(a==='save-pq-notes')b.onclick=savePqNotes; if(a==='add-interface')b.onclick=addInterface; if(a==='save-interfaces')b.onclick=saveInterfaces; if(a==='apply-prestart-status')b.onclick=applyPrestartStatus; if(a==='new-monitoring')b.onclick=()=>openMonitoringModal(); if(a==='save-performance-notes')b.onclick=savePerformanceNotes; if(a==='apply-close-status')b.onclick=applyCloseStatus; });
    $$('[data-edit-contractor]').forEach(b=>b.onclick=()=>openContractorModal(b.dataset.editContractor));
    $$('[data-edit-monitoring]').forEach(b=>b.onclick=()=>openMonitoringModal(b.dataset.editMonitoring));
    $$('.crit-range').forEach(el=>el.oninput=()=>{const c=activeContract();c.criticality=c.criticality||{};c.criticality[el.dataset.key]=Number(el.value);$('#crit-'+el.dataset.key).textContent=el.value;save();const r=criticalityResult(c);$('#critTotal').textContent=`${r.total}/25`;$('#critProgress').style.width=`${r.total/25*100}%`;});
    $$('.pq-score').forEach(el=>el.onchange=()=>{const c=activeContract();c.prequal=c.prequal||{scores:{},blockers:{}};c.prequal.scores[el.dataset.key]=Number(el.value);save();updatePqResult();});
    $$('.pq-blocker').forEach(el=>el.onchange=()=>{const c=activeContract();c.prequal.blockers=c.prequal.blockers||{};c.prequal.blockers[el.dataset.key]=el.checked;save();updatePqResult();});
    $$('.ps-state').forEach(el=>el.onclick=()=>{const c=activeContract();c.prestart=c.prestart||{checks:{},interfaces:[]};c.prestart.checks[el.dataset.id]=el.dataset.value;save();render();});
    $$('[data-remove-interface]').forEach(b=>b.onclick=()=>{const c=activeContract();c.prestart.interfaces.splice(Number(b.dataset.removeInterface),1);save();render();});
    $$('.perf-range').forEach(el=>el.oninput=()=>{const c=activeContract();c.performance[el.dataset.key]=Number(el.value);save();$('#dim-'+el.dataset.key).textContent=`${el.value}%`;updatePerfResult();});
    $$('.perf-blocker').forEach(el=>el.onchange=()=>{const c=activeContract();c.performance.blockers=c.performance.blockers||{};c.performance.blockers[el.dataset.key]=el.checked;save();updatePerfResult();});
    const search=$('#contractorSearch'); if(search)search.oninput=()=>{const q=search.value.toLowerCase().trim();const rows=state.contractors.filter(x=>(x.name+' '+x.rif+' '+x.contact).toLowerCase().includes(q));$('#contractorsTable').innerHTML=contractorsTable(rows);bindView();};
  }

  function updatePqResult(){const r=prequalResult(activeContract());$('#pqScore').textContent=`${pct(r.score)}%`;$('#pqProgress').style.width=`${r.score}%`;$('#pqDecision').textContent=r.decision;}
  function updatePerfResult(){const r=performanceResult(activeContract());$('#perfScore').textContent=`${pct(r.score)}%`;$('#perfProgress').style.width=`${r.score}%`;$('#perfDecision').textContent=r.decision;}
  function saveContractMeta(){const c=activeContract();c.status=$('#contractStatus').value;c.scope=$('#contractScope').value.trim();save();notify('Contrato actualizado.','success');render();}
  function editTasks(){const c=activeContract();const txt=prompt('Tareas críticas separadas por coma:',(c.tasks||[]).join(', '));if(txt===null)return;c.tasks=txt.split(',').map(x=>x.trim()).filter(Boolean);save();render();}
  function savePqNotes(){activeContract().prequal.notes=$('#pqNotes').value.trim();save();notify('Criterio de precalificación guardado.','success');}
  function addInterface(){const c=activeContract();c.prestart=c.prestart||{checks:{},interfaces:[]};c.prestart.interfaces.push({activity:'',client:'',contractor:'',primacy:'',gap:'',control:''});save();render();}
  function saveInterfaces(){const c=activeContract();$$('[data-interface]').forEach(card=>{const i=Number(card.dataset.interface);card.querySelectorAll('.int-field').forEach(el=>c.prestart.interfaces[i][el.dataset.k]=el.value.trim());});save();notify('Mapa de interfaces actualizado.','success');}
  function applyPrestartStatus(){const c=activeContract();const r=prestartResult(c);if(r.decision==='AUTORIZAR INICIO')c.status='Habilitado';else c.status='Pendiente de habilitación';save();notify(`Estado actualizado: ${c.status}.`,r.decision==='AUTORIZAR INICIO'?'success':'warn');render();}
  function savePerformanceNotes(){const c=activeContract();c.performance.strengths=$('#perfStrengths').value.trim();c.performance.gaps=$('#perfGaps').value.trim();save();notify('Aprendizajes de cierre guardados.','success');}
  function applyCloseStatus(){const c=activeContract();c.status='En cierre';save();notify('Contrato movido a fase de cierre.','success');render();}

  function openModal(titleText,bodyHtml,onSave){$('#modalTitle').textContent=titleText;$('#modalBody').innerHTML=bodyHtml;$('#modalBackdrop').hidden=false;const form=$('#modalBody form');if(form)form.onsubmit=e=>{e.preventDefault();onSave(new FormData(form));};}
  function closeModal(){$('#modalBackdrop').hidden=true;$('#modalBody').innerHTML='';}
  function openContractorModal(id){const x=id?state.contractors.find(c=>c.id===id):null;openModal(x?'Editar contratista':'Registrar contratista',`<form><div class="form-grid"><div class="field full"><label>Razón social</label><input class="input" name="name" required value="${esc(x?.name||'')}"></div><div class="field"><label>RIF</label><input class="input" name="rif" value="${esc(x?.rif||'')}"></div><div class="field"><label>Estado general</label><select class="select" name="status">${selectHtml(['En evaluación','Apta','Apta con condiciones','Restringida'],x?.status||'En evaluación')}</select></div><div class="field"><label>Contacto</label><input class="input" name="contact" value="${esc(x?.contact||'')}"></div><div class="field"><label>Teléfono</label><input class="input" name="phone" value="${esc(x?.phone||'')}"></div><div class="field full"><label>Correo</label><input class="input" type="email" name="email" value="${esc(x?.email||'')}"></div><div class="field full"><label>Notas</label><textarea class="textarea" name="notes">${esc(x?.notes||'')}</textarea></div></div><div class="actions"><button type="button" class="btn btn-ghost" data-close-modal>Cancelar</button><button class="btn btn-primary" type="submit">Guardar</button></div></form>`,fd=>{const obj={id:x?.id||uid('co'),name:fd.get('name').trim(),rif:fd.get('rif').trim(),status:fd.get('status'),contact:fd.get('contact').trim(),phone:fd.get('phone').trim(),email:fd.get('email').trim(),notes:fd.get('notes').trim()};if(x)Object.assign(x,obj);else state.contractors.push(obj);save();closeModal();notify('Contratista guardada.','success');render();});bindModalButtons();}
  function openContractModal(){if(!state.contractors.length){notify('Primero registra una contratista.','warn');return;}openModal('Nuevo contrato',`<form><div class="form-grid"><div class="field full"><label>Nombre / alcance corto</label><input class="input" name="title" required placeholder="Ej. Mantenimiento eléctrico de subestación"></div><div class="field"><label>Contratista</label><select class="select" name="contractorId">${state.contractors.map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('')}</select></div><div class="field"><label>Centro de trabajo / ubicación</label><input class="input" name="site"></div><div class="field"><label>Fecha inicio</label><input class="input" type="date" name="start"></div><div class="field"><label>Fecha fin prevista</label><input class="input" type="date" name="end"></div><div class="field"><label>N.º trabajadores</label><input class="input" type="number" min="0" name="workers" value="0"></div><div class="field"><label>N.º subcontratistas</label><input class="input" type="number" min="0" name="subcontractors" value="0"></div><div class="field full"><label>Descripción del alcance</label><textarea class="textarea" name="scope"></textarea></div><div class="field full"><label>Tareas críticas (separadas por coma)</label><input class="input" name="tasks" placeholder="Espacios confinados, trabajo en caliente..."></div></div><div class="actions"><button type="button" class="btn btn-ghost" data-close-modal>Cancelar</button><button class="btn btn-primary" type="submit">Crear contrato</button></div></form>`,fd=>{const obj={id:uid('ct'),contractorId:fd.get('contractorId'),title:fd.get('title').trim(),site:fd.get('site').trim(),start:fd.get('start'),end:fd.get('end'),workers:Number(fd.get('workers'))||0,subcontractors:Number(fd.get('subcontractors'))||0,status:'Borrador',scope:fd.get('scope').trim(),tasks:fd.get('tasks').split(',').map(x=>x.trim()).filter(Boolean),criticality:{exposure:1,severity:1,complexity:1,interfaces:1,subcontracting:1},prequal:{scores:Object.fromEntries(PREQUAL.map(x=>[x.id,0])),blockers:{criticalCompetence:false,legalGap:false,criticalControl:false},notes:''},prestart:{checks:{},interfaces:[]},monitoring:[],performance:{management:0,operations:0,actions:0,learning:0,results:0,blockers:{criticalLegal:false,criticalControl:false,overdueCritical:false,highPotential:false},strengths:'',gaps:''}};state.contracts.push(obj);state.activeContractId=obj.id;save();closeModal();notify('Contrato creado. Comienza por clasificar su criticidad.','success');setView('criticality');});bindModalButtons();}
  function openMonitoringModal(id){const c=activeContract();const x=id?(c.monitoring||[]).find(a=>a.id===id):null;openModal(x?'Editar seguimiento':'Nuevo registro de seguimiento',`<form><div class="form-grid"><div class="field"><label>Fecha</label><input class="input" type="date" name="date" required value="${esc(x?.date||new Date().toISOString().slice(0,10))}"></div><div class="field"><label>Tipo</label><select class="select" name="type">${selectHtml(['Inspección','Verificación','Reunión','Incidente','Cuasi accidente','Cambio','Auditoría'],x?.type||'Verificación')}</select></div><div class="field"><label>Severidad</label><select class="select" name="severity">${selectHtml(['Observación','Menor','Mayor','Crítica'],x?.severity||'Menor')}</select></div><div class="field"><label>Estado</label><select class="select" name="status">${selectHtml(['Abierta','En curso','Cerrada'],x?.status||'Abierta')}</select></div><div class="field full"><label>Hallazgo / decisión</label><textarea class="textarea" name="finding" required>${esc(x?.finding||'')}</textarea></div><div class="field"><label>Responsable</label><input class="input" name="owner" value="${esc(x?.owner||'')}"></div><div class="field"><label>Fecha compromiso</label><input class="input" type="date" name="due" value="${esc(x?.due||'')}"></div></div><div class="actions"><button type="button" class="btn btn-ghost" data-close-modal>Cancelar</button><button class="btn btn-primary" type="submit">Guardar</button></div></form>`,fd=>{const obj={id:x?.id||uid('m'),date:fd.get('date'),type:fd.get('type'),severity:fd.get('severity'),status:fd.get('status'),finding:fd.get('finding').trim(),owner:fd.get('owner').trim(),due:fd.get('due')};if(x)Object.assign(x,obj);else{c.monitoring=c.monitoring||[];c.monitoring.push(obj);}save();closeModal();notify('Seguimiento actualizado.','success');render();});bindModalButtons();}
  function bindModalButtons(){$$('[data-close-modal]').forEach(b=>b.onclick=closeModal);}

  function exportState(){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`movidasst-contratistas-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href);notify('Respaldo exportado.','success');}
  function importState(file){const r=new FileReader();r.onload=()=>{try{const data=JSON.parse(r.result);if(!data.contractors||!data.contracts)throw new Error('Formato no válido');state=data;save();notify('Respaldo importado.','success');render();}catch(e){notify('No se pudo importar el archivo.','warn');}};r.readAsText(file);}

  // Global events
  $$('.nav-item').forEach(b=>b.onclick=()=>setView(b.dataset.view));
  picker.onchange=()=>{state.activeContractId=picker.value;save();render();};
  $('#quickContractBtn').onclick=openContractModal;
  $('#printBtn').onclick=()=>window.print();
  $('#menuToggle').onclick=()=>$('#sidebar').classList.toggle('open');
  $('#modalClose').onclick=closeModal;
  $('#modalBackdrop').onclick=e=>{if(e.target.id==='modalBackdrop')closeModal();};
  $('#importFile').onchange=e=>{if(e.target.files?.[0])importState(e.target.files[0]);e.target.value='';};
  window.addEventListener('hashchange',()=>{currentView=location.hash.replace('#/','')||'dashboard';render();});
  window.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal();});

  render();
